/* Throwaway: fetch the permissive chessnut piece silhouettes (Apache-2.0,
   github.com/LexLuengas/chessnut-pieces — black set = clean single-fill paths),
   strip hardcoded fills so CSS controls color, and emit piece-sets.js for the
   generative-table sandbox. Also authors a typographic "letter" set. */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const __dirname = dirname(fileURLToPath(import.meta.url));

const TYPES = { K: "bK", Q: "bQ", R: "bR", B: "bB", N: "bN", P: "bP" };
const BASE = "https://raw.githubusercontent.com/LexLuengas/chessnut-pieces/HEAD/";

function extractPaths(svg) {
  // grab every <path d="..."> and keep ONLY the geometry (drop fill/style/id)
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"[^>]*\/?>/g)].map((m) => m[1]);
  return ds.map((d) => `<path d="${d}"/>`).join("");
}

const chessnut = { vb: "0 0 800 800", inner: {} };
for (const [type, file] of Object.entries(TYPES)) {
  const svg = await fetch(BASE + file + ".svg").then((r) => r.text());
  const inner = extractPaths(svg);
  if (!inner) throw new Error("no paths in " + file);
  chessnut.inner[type] = inner;
  console.log(file, "->", inner.length, "chars");
}

// authored typographic set — renders in the world's display font, recolorable
const letter = { vb: "0 0 800 800", inner: {} };
for (const t of ["K", "Q", "R", "B", "N", "P"]) {
  letter.inner[t] = `<text x="400" y="404" text-anchor="middle" dominant-baseline="central" font-family="inherit" font-weight="700" font-size="600" letter-spacing="0">${t}</text>`;
}

const data = { chessnut, letter };
const banner = `chessnut silhouettes: Apache-2.0 (github.com/LexLuengas/chessnut-pieces).
   'letter' set: authored here (permissive). Fills/strokes are CSS-driven.`;

// 1) sandbox global (for generative-table.html)
const js = `/* AUTO-GENERATED by build-pieces.mjs — throwaway sandbox asset.
   ${banner} */
window.PIECE_SETS = ${JSON.stringify(data)};
`;
writeFileSync(join(__dirname, "piece-sets.js"), js);

// 2) typed module for the real app (src/lib/table/pieceSets.ts)
const ts = `/* AUTO-GENERATED by research/designs/build-pieces.mjs — do not edit by hand.
   ${banner} */
export type PieceType = "K" | "Q" | "R" | "B" | "N" | "P";
export interface PieceSet { vb: string; inner: Record<PieceType, string>; }
export const PIECE_SETS: Record<string, PieceSet> = ${JSON.stringify(data)};
`;
const tsPath = join(__dirname, "..", "..", "src", "lib", "table", "pieceSets.ts");
writeFileSync(tsPath, ts);
console.log("\nwrote piece-sets.js (" + js.length + " bytes) + src/lib/table/pieceSets.ts");
